baseURL = 'https://jsonvoorhees.sh/'
languageCode = 'en-us'
title = 'JSON_Voorhees'
theme = 'PaperMod'
enableRobotsTXT = true

[params]
  mainSections = ["posts"]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false

[params.homeInfoParams]
  Title = 'JSON_Voorhees'
  Content = 'Red Teaming Blog of JSON_Voorhees'

[markup.highlight]
  noClasses = false
  lineNos = true

[[menu.main]]
  name = 'Posts'
  url = '/posts/'
  weight = 10

[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = 20

[[menu.main]]
  name = 'Disclosure'
  url = '/disclosure/'
  weight = 30