baseURL = 'https://jsonvoorhees.sh/'
languageCode = 'en-us'
title = 'JSON_Voorhees'
theme = 'PaperMod'
enableRobotsTXT = true

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false

[params.homeInfoParams]
  Title = 'JSON_Voorhees'
  Content = 'Michael, known more commonly as JSON_Voorhees in AI hacking circles. I red team AI, write speculative fiction, and develop indie games. This little corner is for AI red teaming -- findings, methodology, and whatever else my wacky imagination cracks out to help break--err, responsibly test--AI.'

[[menu.main]]
  name = 'Posts'
  url = '/posts/'
  weight = 10
[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = 20
[[menu.main]]
  name = 'Disclosure'
  url = '/disclosure/'
  weight = 30

[markup.highlight]
  noClasses = false
  lineNos = true